<?php

namespace Rofil\Simple\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsCategoryRepository extends EntityRepository
{
}
